Enhanced oeb checks to use gpio defaults for caravel/caravan and gpio configuration for openframe
Signed-off-by: D. Mitch Bailey <d.mitch.bailey@gmail.com>

diff --git a/src/cf_precheck/be_checks/run_oeb_check b/src/cf_precheck/be_checks/run_oeb_check
--- a/src/cf_precheck/be_checks/run_oeb_check
+++ b/src/cf_precheck/be_checks/run_oeb_check
@@ -129,6 +129,7 @@ ERROR: Could not create $WORK_ROOT/cvcrc.oeb"
 fi
 
 if [[ $DESIGN_NAME == *user_analog_project_wrapper ]]; then
+	PADRING_TYPE=caravan
 	cat >$WORK_ROOT/cvc.oeb.script <<-cvcin
 		c 6
 		gn io_in[0]
@@ -278,6 +279,7 @@ if [[ $DESIGN_NAME == *user_analog_project_wrapper ]]; then
 		q
 	cvcin
 elif [[ $DESIGN_NAME == *user_project_wrapper ]]; then
+	PADRING_TYPE=caravel
 	cat >$WORK_ROOT/cvc.oeb.script <<-cvcin
 		c 6
 		gn io_in[0]
@@ -632,7 +634,30 @@ if [[ $WORK_ROOT != $LOG_ROOT ]]; then
 	cp $WORK_ROOT/cvc.oeb.log $LOG_ROOT/.
 fi
 
-awk '
+# Remove comments from user_defines.v file
+if [[ -f verilog/rtl/user_defines.v ]]; then
+	perl -0777 -pe 's://.*?$::mg; s:/\*.*?\*/::sg' verilog/rtl/user_defines.v >$WORK_ROOT/user_defines.v
+else
+	echo "Missing verilog/rtl/user_defines.v"
+	touch $WORK_ROOT/user_defines.v
+fi
+
+awk -v padring=${PADRING_TYPE:-} '
+	BEGIN {
+		gpio_config[0] = "MGMT_STD_INPUT_NOPULL";
+		gpio_config[1] = "MGMT_STD_INPUT_NOPULL";
+		gpio_config[2] = "MGMT_STD_INPUT_NOPULL";
+		gpio_config[3] = "MGMT_STD_INPUT_PULLUP";
+		gpio_config[4] = "MGMT_STD_INPUT_NOPULL";
+	}
+	/^`define USER_CONFIG_GPIO/ {
+		split($2, tokens, /_/); # Ex. USER_CONFIG_GPIO_29_INIT
+		gpio_index = tokens[4];
+		if ( padring_type == "caravan" && gpio_index > 24 ) {
+			gpio_index -= 11;
+		}
+		gpio_config[gpio_index] = gensub(/`GPIO_MODE_/, "", 1, $3); # Save the contstant
+	}
 	/^> gn io_in/ {
 		net = gensub(/.*\[([0-9]*)\]/, "\\1", 1);
 		getline;
@@ -681,7 +706,7 @@ awk '
 			getline;
 		}
 		if ( out_min[net] == out_sim[net] && out_sim[net] == out_max[net] ) {
-			fixed[net] = out_sim[net];
+			fixed_out[net] = out_sim[net];
 		}
 	}
 	/^> gn io_oeb/ {
@@ -713,39 +738,230 @@ awk '
 			}
 			getline;
 		}
+		if ( oeb_min[net] == oeb_sim[net] && oeb_sim[net] == oeb_max[net] ) {
+			fixed_oeb[net] = oeb_sim[net];
+		}
+	}
+	function IsLow(signal) {
+		return ( signal ~ /vss/ || signal ~ /VGND/ );
+	}
+	function IsHigh(signal) {
+		return ( signal ~ /vccd/ || signal ~ /vdd/ || signal ~ /VPWR/ );
 	}
 	END {
 		#print "oeb connections:", length(oeb_connections);
-		print " gpio |   in   |   out  | analog |  oeb min/sim/max  | Message";
+		print " gpio |   in   |   out  | analog |  oeb min/sim/max  | configuration";
 		     #"  xx  | xxxxxx | xxxxxx | xxxxxx | vxxx*/vxxx*/vxxx* |
 		PROCINFO["sorted_in"] = "@ind_num_asc";
+		delete messages;
 		for ( i in oeb_connections ) {
 			printf "  %2d  | %6s | %6s | %6s | %5s/%5s/%5s | ", \
 				i, (in_connections[i] == 0) ? "" : sprintf("%6d", in_connections[i]), \
 				(out_connections[i] == 0) ? "" :
-					(i in fixed) ? fixed[i] : sprintf("%6d", out_connections[i]), \
+					(i in fixed_out) ? fixed_out[i] : sprintf("%6d", out_connections[i]), \
 				(analog_connections[i] == 0) ? "" : sprintf("%6d", analog_connections[i]), \
 				oeb_min[i], oeb_sim[i], oeb_max[i];
-			if ( analog_connections[i] > 0 ) {
-				if ( in_connections[i] > 0 || (out_connections[i] > 0 && ! (i in fixed)) ) {  # both digital and analog
-					printf "Warning: both analog and digital connections";
-				} else if ( ! ( oeb_sim[i] ~ /vccd/ || oeb_sim[i] ~ /vdd/ || oeb_sim[i] ~ /VPWR/ ) ) {  # analog signals should disable output
-					printf "Warning: oeb expected high for analog";
+			# gpio defaults check
+			printf "%s ", gpio_config[i];
+			error_count = length(messages);
+			switch(gpio_config[i]) {
+			case /MGMT_STD_INPUT_.*/: {
+				if ( out_connections[i] > 0 && ! (i in fixed_out) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user output connection to management input gpio ignored", i);
 				}
-			} else if ( in_connections[i] > 0 && out_connections[i] == 0 ) {
-				if ( ! ( oeb_sim[i] ~ /vccd/ || oeb_sim[i] ~ /vdd/ || oeb_sim[i] ~ /VPWR/ ) ) {  # input only signals should never enable output
-					printf "Warning: oeb expected high for input only";
+				if ( oeb_connections[i] > 0 && ! (i in fixed_oeb) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user oeb to connection management input gpio ignored", i);
 				}
-			} else if ( out_connections[i] > 0 && ! (i in fixed) ) {
-				if ( ! ( oeb_min[i] ~ /vss/ || oeb_min[i] ~ /VGND/ ) ) {  # output signals must be enable-able
-					printf "ERROR: oeb must have possible low for output";
-				} else if ( in_connections[i] > 0 && ( oeb_sim[i] ~ /vss/ || oeb_min[i] ~ /VGND/ ) ) {  # input is always driven by user output in user mode
-					printf "Warning: output always drives input. sky130: OK for pull up/down.";
+				if ( analog_connections[i] ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: analog connection to management input gpio", i);
 				}
+				break;
+			}
+			case /MGMT_STD_OUTPUT/: {
+				if ( in_connections[i] > 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: user input connection to management output gpio - undriven", i);
+				}
+				if ( out_connections[i] > 0 && ! (i in fixed_out) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user output connection to management output gpio ignored", i);
+				}
+				if ( oeb_connections[i] > 0 && ! (i in fixed_oeb) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user oeb to connection management output gpio ignored", i);
+				}
+				if ( analog_connections[i] ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: analog connection to management output gpio", i);
+				}
+				break;
+			}
+			case /MGMT_STD_BIDIRECTIONAL/: {
+				if ( out_connections[i] > 0 && ! (i in fixed_out) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user output connection to management bidirectional gpio ignored", i);
+				}
+				if ( oeb_connections[i] > 0 && ! (i in fixed_oeb) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user oeb to connection management bidirectional gpio ignored", i);
+				}
+				if ( analog_connections[i] ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: analog connection to management bidirectional gpio", i);
+				}
+				break;
+			}
+			case /MGMT_STD_ANALOG/: {
+				if ( in_connections[i] > 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: user input connection to analog gpio - undriven", i);
+				}
+				if ( out_connections[i] > 0 && ! (i in fixed_out) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user output connection to analog gpio ignored", i);
+				}
+				if ( oeb_connections[i] > 0 && ! (i in fixed_oeb) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user oeb to connection analog gpio ignored", i);
+				}
+				break;
+			}
+			case /USER_STD_INPUT_NOPULL/: {
+				if ( in_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: missing user input connection", i);
+				}
+				if ( out_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: user mode requires output connection", i);
+				}
+				if ( oeb_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: user mode requires oeb connection", i);
+				}
+				if ( analog_connections[i] > 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: analog connection to user input gpio", i);
+				}
+				break;
+			}
+			case /USER_STD_INPUT_PULLDOWN/: {
+				if ( in_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: missing user input connection", i);
+				}
+				if ( out_connections[i] == 0 || ! IsLow(out_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: user pulldown mode requires low output", i);
+				}
+				if ( oeb_connections[i] == 0 || ! IsLow(oeb_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: user pulldown mode requires low oeb", i);
+				}
+				if ( analog_connections[i] ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: analog connection to user input gpio", i);
+				}
+				break;
+			}
+			case /USER_STD_INPUT_PULLUP/: {
+				if ( in_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: missing user input connection", i);
+				}
+				if ( out_connections[i] == 0 || ! IsHigh(out_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: user pullup mode requires high output", i);
+				}
+				if ( oeb_connections[i] == 0 || ! IsLow(oeb_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: user pullup mode requires low oeb", i);
+				}
+				if ( analog_connections[i] ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: analog connection to user input gpio", i);
+				}
+				break;
+			}
+			case /USER_STD_OUTPUT/: {
+				if ( in_connections[i] > 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: user input connection to user output gpio - undriven", i);
+				}
+				if ( out_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: missing user output connection for output gpio", i);
+				} else if ( i in fixed_out ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user output fixed at %s", i, fixed_out[i]);
+				}
+				if ( oeb_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: missing user oeb for output gpio", i);
+				} else if ( IsHigh(oeb_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user oeb is always high - output disabled", i);
+				} else if ( ! IsLow(oeb_min[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user oeb is never low - output never enabled", i);
+				}
+				if ( analog_connections[i] ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: analog connection to user output gpio", i);
+				}
+				break;
+			}
+			case /USER_STD_BIDIRECTIONAL/: {
+				if ( in_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: missing user input connection to bidirectional gpio", i);
+				}
+				if ( out_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: missing user output connection for bidirectional gpio", i);
+				} else if ( i in fixed_out ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user output fixed at %s", i, fixed_out[i]);
+				}
+				if ( oeb_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: missing user oeb for bidirection gpio", i);
+				} else if ( IsHigh(oeb_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: bidirectional user oeb is always high - always input mode", i);
+				} else if ( IsLow(oeb_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: bidirectional user oeb is always low - always output mode", i);
+				} else {
+					if ( ! IsLow(oeb_min[i]) ) {
+						messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user oeb is never low - bidirectional output never enabled", i);
+					}
+					if ( ! IsHigh(oeb_max[i]) ) {
+						messages[length(messages)+1] = sprintf("GPIO %2d: Warning: user oeb is never high - bidirectional input never enabled", i);
+					}
+				}
+				if ( analog_connections[i] ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: analog connection to user bidirectional gpio", i);
+				}
+				break;
+			}
+			case /USER_STD_ANALOG/: {
+				if ( in_connections[i] > 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: user input connection to analog gpio - undriven", i);
+				}
+				if ( out_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: user mode requires output connection", i);
+				}
+				if ( oeb_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: user mode requires oeb connection", i);
+				}
+				if ( analog_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: missing analog connection to user analog gpio", i);
+				}
+				break;
+			}
+			default: {
+				printf "unknown mode";
+				if ( analog_connections[i] > 0 ) {
+					if ( in_connections[i] > 0 || (out_connections[i] > 0 && ! (i in fixed_out)) ) {  # both digital and analog
+						printf "Warning: both analog and digital connections ";
+					} else if ( ! IsHigh(oeb_sim[i]) ) {  # analog signals should disable output
+						printf "Warning: oeb expected high for analog ";
+					}
+				} else if ( in_connections[i] > 0 && out_connections[i] == 0 ) {
+					if ( ! IsHigh(oeb_sim[i]) ) {  # input only signals should never enable output
+						printf "Warning: oeb expected high for input only ";
+					}
+				} else if ( out_connections[i] > 0 && ! (i in fixed_out) ) {
+					if ( ! IsLow(oeb_min[i]) ) {  # output signals must be enable-able
+						printf "ERROR: oeb must have possible low for output ";
+					} else if ( in_connections[i] > 0 && IsLow(oeb_sim[i]) ) {  # input is always driven by user output in user mode
+						printf "Warning: output always drives input. sky130: OK for pull up/down. ";
+					}
+				}
+				break;
+			}
+			}
+			new_errors = length(messages) - error_count;
+			if ( new_errors > 0 ) {
+				printf("%d warnings/errors", new_errors);
 			}
 			printf "\n";
 		}
-	}' $LOG_ROOT/cvc.oeb.log |
+		if ( length(messages) == 0 ) {
+			printf("\nNo warnings or errors detected\n");
+		} else {
+			printf("\n*** Detected the following warnings and/or errors: ***\n");
+		}
+		for ( line = 1; line <= length(messages); line++) {
+			print messages[line];
+		}
+	}' $WORK_ROOT/user_defines.v $LOG_ROOT/cvc.oeb.log |
 	tee $WORK_ROOT/cvc.oeb.report
 
 if [[ $WORK_ROOT != $SIGNOFF_ROOT ]]; then
diff --git a/src/cf_precheck/be_checks/run_openframe_check b/src/cf_precheck/be_checks/run_openframe_check
--- a/src/cf_precheck/be_checks/run_openframe_check
+++ b/src/cf_precheck/be_checks/run_openframe_check
@@ -127,7 +127,7 @@ ERROR: Could not create $WORK_ROOT/cvcrc.oeb"
 	sed 's/cvc.log/cvc.oeb.log/' $WORK_ROOT/cvcrc >$WORK_ROOT/cvcrc.oeb
 fi
 
-if [[ $DESIGN_NAME == *openframe_project_wrapper ]]; then
+if [[ "$DESIGN_NAME" == *openframe_project_wrapper ]]; then
 	echo "c 6" >$WORK_ROOT/cvc.oeb.script
 	for ((i = 0; i <= 43; i++)); do
 		cat >>$WORK_ROOT/cvc.oeb.script <<-cvcin
@@ -152,7 +152,7 @@ if [[ $DESIGN_NAME == *openframe_project_wrapper ]]; then
 	done
 	echo "q" >>$WORK_ROOT/cvc.oeb.script
 else
-	echo "ERROR: unrecognized top block $DESIGN_NAME"
+	echo "ERROR: unrecognized top block >$DESIGN_NAME<"
 	exit 3
 fi
 
@@ -283,10 +283,21 @@ awk '
 			printf "?";
 		}
 	}
+	function IsLow(signal) {
+		return ( signal ~ /vss/ || signal ~ /VGND/ || signal == 0 );
+	}
+	function IsHigh(signal) {
+		return ( signal ~ /vccd/ || signal ~ /vdd/ || signal ~ /VPWR/ || signal == 1 );
+	}
 	END {
+		GPIO_TYPE["000"] = "USER_STD_ANALOG";
+		GPIO_TYPE["001"] = "USER_STD_INPUT";
+		GPIO_TYPE["110"] = "USER_STD_INPUT_OUTPUT";
+		GPIO_TYPE["111"] = "USER_STD_INPUT_PULL";
 		#print "oeb connections:", length(oeb_connections);
 		print " gpio |   in   |   out  | analog |  oeb min/sim/max  | Message";
 		     #"  xx  | xxxxxx | xxxxxx | xxxxxx | vxxx*/vxxx*/vxxx* |
+		delete messages;
 		for ( i in oeb_connections ) {
 			oeb_min[i] = ReplaceLoopback(oeb_min[i]);
 			oeb_sim[i] = ReplaceLoopback(oeb_sim[i]);
@@ -297,23 +308,6 @@ awk '
 					(i in fixed) ? fixed[i] : sprintf("%6d", out_connections[i]), \
 				(analog_connections[i] == 0) ? "" : sprintf("%6d", analog_connections[i]), \
 				oeb_min[i], oeb_sim[i], oeb_max[i];
-			if ( analog_connections[i] > 0 ) {
-				if ( in_connections[i] > 0 || (out_connections[i] > 0 && ! (i in fixed)) ) {  # both digital and analog
-					printf "Warning: both analog and digital connections";
-				} else if ( ! ( oeb_sim[i] ~ /vccd/ || oeb_sim[i] ~ /vdd/ ) ) {  # analog signals should disable output
-					printf "Warning: oeb expected high for analog";
-				}
-			} else if ( in_connections[i] > 0 && out_connections[i] == 0 ) {
-				if ( ! ( oeb_sim[i] ~ /vccd/ || oeb_sim[i] ~ /vdd/ ) ) {  # input only signals should never enable output
-					printf "Warning: oeb expected high for input only";
-				}
-			} else if ( out_connections[i] > 0 && ! (i in fixed) ) {
-				if ( oeb_min[i] !~ /vss/ ) {  # output signals must be enable-able
-					printf "ERROR: oeb must have possible low for output";
-				} else if ( in_connections[i] > 0 && oeb_sim[i] ~ /vss/ ) {  # input is always driven by user output in user mode
-					printf "Warning: output always drives input. sky130: OK for pull up/down.";
-				}
-			}
 			PrintBit(dm2_sim[i], dm2_connections[i]);
 			PrintBit(dm1_sim[i], dm1_connections[i]);
 			PrintBit(dm0_sim[i], dm0_connections[i]);
@@ -325,7 +319,167 @@ awk '
 			PrintBit(ib_mode_sim[i], ib_mode_connections[i]);
 			PrintBit(inp_dis_sim[i], inp_dis_connections[i]);
 			PrintBit(holdover_sim[i], holdover_connections[i]);
+			gpio_config = GPIO_TYPE[dm2[i] dm1[i] dm0[i]];
+			if ( gpio_config == "USER_STD_INPUT_PULL" ) {
+				if ( IsHigh(out_sim[i]) ) {
+					gpio_config = "USER_STD_INPUT_PULLUP";
+				} else {
+					gpio_config = "USER_STD_INPUT_PULLDOWN";
+				}
+			}
+			if ( gpio_config == "USER_STD_OUTPUT" && IsLow(input_dis_sim[i]) ) {
+				gpio_config = "USER_STD_BIDIRECTIONAL";
+			}
+			printf " -> %s ", gpio_config ? gpio_config : "UNKNOWN";
+			error_count = length(messages);
+			switch(gpio_config) {
+			case /USER_STD_INPUT_NOPULL/: {
+				if ( in_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: missing user input connection", i);
+				}
+				if ( out_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: output connection required", i);
+				}
+				if ( oeb_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: oeb connection required", i);
+				}
+				if ( analog_connections[i] > 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: analog connection to user input gpio", i);
+				}
+				break;
+			}
+			case /USER_STD_INPUT_PULLDOWN/: {
+				if ( in_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: missing user input connection", i);
+				}
+				if ( out_connections[i] == 0 || ! IsLow(out_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: pulldown mode requires low output", i);
+				}
+				if ( oeb_connections[i] == 0 || ! IsLow(oeb_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: pulldown mode requires low oeb", i);
+				}
+				if ( analog_connections[i] ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: analog connection to user input gpio", i);
+				}
+				break;
+			}
+			case /USER_STD_INPUT_PULLUP/: {
+				if ( in_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: missing user input connection", i);
+				}
+				if ( out_connections[i] == 0 || ! IsHigh(out_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: pullup mode requires high output", i);
+				}
+				if ( oeb_connections[i] == 0 || ! IsLow(oeb_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: pullup mode requires low oeb", i);
+				}
+				if ( analog_connections[i] ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: analog connection to user input gpio", i);
+				}
+				break;
+			}
+			case /USER_STD_OUTPUT/: {
+				if ( in_connections[i] > 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: input connection to output gpio - undriven", i);
+				}
+				if ( out_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: missing output connection for output gpio", i);
+				} else if ( i in fixed_out ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: output fixed at %s", i, fixed_out[i]);
+				}
+				if ( oeb_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: missing oeb for output gpio", i);
+				} else if ( IsHigh(oeb_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: oeb is always high - output disabled", i);
+				} else if ( ! IsLow(oeb_min[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: oeb is never low - output never enabled", i);
+				}
+				if ( analog_connections[i] ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: analog connection to output gpio", i);
+				}
+				break;
+			}
+			case /USER_STD_BIDIRECTIONAL/: {
+				if ( in_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: missing input connection to bidirectional gpio", i);
+				}
+				if ( out_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: missing output connection for bidirectional gpio", i);
+				} else if ( i in fixed_out ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: output fixed at %s", i, fixed_out[i]);
+				}
+				if ( oeb_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: missing oeb for bidirection gpio", i);
+				} else if ( IsHigh(oeb_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: bidirectional oeb is always high - always input mode", i);
+				} else if ( IsLow(oeb_sim[i]) ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: bidirectional oeb is always low - always output mode", i);
+				} else {
+					if ( ! IsLow(oeb_min[i]) ) {
+						messages[length(messages)+1] = sprintf("GPIO %2d: Warning: oeb is never low - bidirectional output never enabled", i);
+					}
+					if ( ! IsHigh(oeb_max[i]) ) {
+						messages[length(messages)+1] = sprintf("GPIO %2d: Warning: oeb is never high - bidirectional input never enabled", i);
+					}
+				}
+				if ( analog_connections[i] ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: analog connection to bidirectional gpio", i);
+				}
+				break;
+			}
+			case /USER_STD_ANALOG/: {
+				if ( in_connections[i] > 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: input connection to analog gpio - undriven", i);
+				}
+				if ( out_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: mode requires output connection", i);
+				}
+				if ( oeb_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: mode requires oeb connection", i);
+				}
+				if ( analog_connections[i] == 0 ) {
+					messages[length(messages)+1] = sprintf("GPIO %2d: Warning: missing analog connection to analog gpio", i);
+				}
+				break;
+			}
+			default: {
+				messages[length(messages)+1] = sprintf("GPIO %2d: Warning: unrecognized dm configuration - connectivity confirmation required", i);
+				if ( analog_connections[i] > 0 ) {
+					if ( in_connections[i] > 0 || (out_connections[i] > 0 && ! (i in fixed)) ) {  # both digital and analog
+						messages[length(messages)+1] = sprintf("GPIO %2d: Warning: both analog and digital connections", i);
+					} else if ( ! ( oeb_sim[i] ~ /vccd/ || oeb_sim[i] ~ /vdd/ ) ) {  # analog signals should disable output
+						messages[length(messages)+1] = sprintf("GPIO %2d: Warning: oeb expected high for analog", i);
+					}
+				} else if ( in_connections[i] > 0 && out_connections[i] == 0 ) {
+					if ( ! ( oeb_sim[i] ~ /vccd/ || oeb_sim[i] ~ /vdd/ ) ) {  # input only signals should never enable output
+						messages[length(messages)+1] = sprintf("GPIO %2d: Warning: oeb expected high for input only", i);
+					}
+				} else if ( out_connections[i] > 0 && ! (i in fixed) ) {
+					if ( oeb_min[i] !~ /vss/ ) {  # output signals must be enable-able
+						messages[length(messages)+1] = sprintf("GPIO %2d: ERROR: oeb must have possible low for output", i);
+					} else if ( in_connections[i] > 0 && oeb_sim[i] ~ /vss/ ) {  # input is always driven by output
+						messages[length(messages)+1] = sprintf("GPIO %2d: Warning: output always drives input. sky130: OK for pull up/down.", i);
+					}
+				}
+			}
+			}
+			if ( ! IsLow(vtrip_sim[i]) || ! IsLow(slow_sim[i]) || ! IsLow(analog_pol_sim[i]) || ! IsLow(analog_sel_sim[i]) || \
+					! IsLow(analog_en_sim[i]) || ! IsLow(ib_mode_sim[i]) || ! IsLow(holdover_sim[i]) ) {
+				messages[length(messages)+1] = sprintf("GPIO %2d: Warning: unrecognized configuration - expected vtrip, slow, analog*, ib, hold to be low", i);
+			}
+			new_errors = length(messages) - error_count;
+			if ( new_errors > 0 ) {
+				printf("%d warnings/errors", new_errors);
+			}
 			printf "\n";
+		}
+		if ( length(messages) == 0 ) {
+			printf("\nNo warnings or errors detected\n");
+		} else {
+			printf("\n*** Detected the following warnings and/or errors: ***\n");
+		}
+		for ( line = 1; line <= length(messages); line++) {
+			print messages[line];
 		}
 	}' $LOG_ROOT/cvc.oeb.log |
 	tee $WORK_ROOT/cvc.oeb.report
